language: ruby
cache: bundler
rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
gemfile:
  - test/gemfiles/rails-4.1.gemfile
  - test/gemfiles/rails-4.2.gemfile
matrix:
  include:
    - rvm: 2.3.0
      gemfile: test/gemfiles/rails-5.0.gemfile
